server:
  port: 80

build_name: @project.name@
build_version: @project.version@
spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
