name: Build and Test
run-name: Build test wokflow
on:
    pull_request:
        types:
            - opened
            - edited
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - name: Build
              run: mvn clean compile war:war
            - name: Test
              run: mvn test